Aula 1 - Introdução à gravação de macros

- Quando for gravar uma macro:
"Armazenar macro em" -> Pasta de trabalho pessoal de macros
	- permite usar em várias pastas
	- use o campo de descrição para documentar

- Pratique VBA para não esquecer, além de testar as diferentes possibilidades e presenciar os erros
- Uma macro armazena o zoom da planilha, por exemplo
- Lembre-se de salvar o arquivo como pasta de trabalho havilitada para macros do Excel.